name: backstage-containerization
on:
  push:
    branches:
      - "master"
    paths:
      - "package.json"
      - "packages/app/package.json"
      - "packages/backend/package.json"
      - ".github/workflows/backstage-containerization.yaml"
env:
  IMAGE_NAME: backstage-devx
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - run: yarn install --immutable
      - run: yarn tsc
      - run: yarn build:backend
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
