name: backstage-containerization
on:
  push:
    branches:
      - "master"
    paths:
      - "package.json"
      - "packages/app/package.json"
      - "packages/backend/package.json"
      - ".github/workflows/backstage-containerization.yaml"
env:
  IMAGE_NAME: backstage-devx
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: yarn install
        run: yarn install --immutable
      - name: yarn tsc
        run: yarn tsc
      - name: yarn build:all
        run: yarn build:all
      - name: list packages/backend/dist
        run: ls -la packages/backend/dist
      - name: list packages/app/dist
        run: ls -la packages/app/dist
      - name: yarn build-image
        run: yarn build-image
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
