name: backstage-build
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install --force --verbose
