name: koyeb-deploy

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"

      - name: Build and deploy the application
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: backstage-devx
          service-ports: "7007:http"
          service-routes: "/:7007"
          git-builder: docker
          git-docker-dockerfile: Dockerfile.koyeb
          privileged: true
          skip-cache: true
