name: koyeb-deploy
on:
  push:
    branches:
      - "master"
    paths:
      - "package.json"
      - "packages/app/package.json"
      - "packages/backend/package.json"
      - ".github/workflows/backstage-containerization.yaml"
      - ".github/workflows/koyeb-deploy.yaml"
jobs:
  pull:
    name: koyeb-cli deploy
    runs-on: koyeb/koyeb-cli:latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: koyeb login
        run: koyeb login --token ${{ secrets.KOYEB_TOKEN }}
      - name: koyeb apps list
        run: koyeb apps list
      - name: koyeb services list
        run: koyeb services list
      - name: koyeb service redeploy
        run: koyeb service redeploy backstage-devx/backstage
