name: koyeb-deploy
on:
  push:
    branches:
      - "master"
    paths:
      - "package.json"
      - "packages/app/package.json"
      - "packages/backend/package.json"
      - ".github/workflows/backstage-containerization.yaml"
      - ".github/workflows/koyeb-deploy.yaml"
jobs:
  pull:
    name: koyeb-cli deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: koyeb service redeploy
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          export PATH=$HOME/.koyeb/bin:$PATH
          koyeb version
          koyeb login --token ${{ secrets.KOYEB_TOKEN }}
          koyeb apps list
          koyeb services list
          koyeb service redeploy backstage-devx/backstage
          koyeb services list
          koyeb instances list --app backstage-devx
